spring:
  application:
    name: kindle-reptile-server
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:reptile/mappers/*.xml

#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
